#spring:
#  application:
#    name: api-gateway
server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          routes:
#          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**

            - id: recharge-service
              uri: lb://RECHARGE-SERVICE
              predicates:
                - Path=/recharges/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

