
server:
  port: 8082

spring:
  application:
    name: recharge-service
  datasource:
    url: jdbc:postgresql://localhost:5432/recharge_service_db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      config:
        default:
          loggerLevel=full:



